
name: Node.js CI 
       
       
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.3.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
      
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: clone current
        run: git clone https://github.com/umair901/node-js-getting-started1.git .
      - name: add heroku
        run: git remote add heroku https://heroku:${{ secrets.heroku_api_key }}@git.heroku.com/${{ secrets.heroku_app_name }}.git
      - name: push to heroku
        run: git push heroku master
